### ISSUE TITLE
Missing images from Roundtable 26

### ISSUE THREAD

**Issue by anermina** [CalConnect/cc-admin-documents#16]
[roundtable26rpt.pdf](https://github.com/CalConnect/calconnect.org/blob/main/publications/roundtable26rpt.pdf) document contains images that cannot be loaded in the original document.

![image](https://github.com/user-attachments/assets/ad8d54f3-3dfc-4dca-9a99-55e2e51169d2)

@ronaldtse Is it possible to get these images?

**Comment by ronaldtse** [comment]
@anermina these photos from CalConnect 26 are at:
* https://github.com/CalConnect/calconnect.org/tree/main/old/documents/eventphotos

**Comment by anermina** [comment]
Thank you @ronaldtse !
